### ISSUE TITLE
Wrong check in deploy.bash template

### ISSUE THREAD

**Issue by lijunle** [projectkudu/KuduScript#35]
In [deploy.bash.node.template](https://github.com/projectkudu/KuduScript/blob/254116790e41bc69bce809e46c9998f03addcfc4/lib/templates/deploy.bash.node.template#L15) file, it check on `"$DEPLOYMENT_TEMP/.tmp"`, which is wrong. It should be `$DEPLOYMENT_TEMP/__npmVersion.tmp"`.

Otherwise, the `npm` in package.json engine section is not respected.

**Comment by davidebbo** [comment]
Good catch, thanks!
