### ISSUE TITLE
When running locally %SCM_DNVM_PS_PATH% is ""

### ISSUE THREAD

**Issue by jt000** [projectkudu/KuduScript#44]
I'm attempting to debug changes to my deploy.cmd & have not been able to run it locally (first time I've tried in months). I reverted it back to the default deploy.cmd script and am still seeing the same issue:

```
Installing Kudu Sync
C:\Users\Jason\AppData\Roaming\npm\kudusync -> C:\Users\Jason\AppData\Roaming\npm\node_modules\kudusync\bin\kudusync
kudusync@0.2.3 C:\Users\Jason\AppData\Roaming\npm\node_modules\kudusync
├── commander@2.6.0
├── q@1.1.2
└── minimatch@2.0.1 (brace-expansion@1.1.2)
Handling ASP.NET 5 Web Application deployment.
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object
.
At line:1 char:184
+ ... ;$CmdPathFile='C:\Users\Jason\.dnx\temp-set-envvars.cmd';& ''  instal ...
+                                                                ~~
    + CategoryInfo          : InvalidOperation: (:String) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression

Failed exitCode=1, command=PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [
System.Threading.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile='"C:\Users\Jason\.dnx\temp-set-envvars.cmd"';& '' " install 1.0.0-beta5 -arch x86 -r
clr
An error has occurred during web site deployment.
```

Apparently, when running locally my SCM_DNVM_PS_PATH environment variable is not defined. When run in Azure SCM it runs just fine.

I feel like I'm missing something obvious on my part, since I haven't found anyone else having this issue. 

Any ideas?

**Comment by jt000** [comment]
I resolved this for myself by adding the following to my deploy.cmd:

```
IF "%SCM_DNVM_PS_PATH%"=="" (
    SET SCM_DNVM_PS_PATH="%USERPROFILE%\.dnx\bin\dnvm.ps1"
)
```

Curious if this is what is expected (if so, maybe should be added to the template) or if there was another way that this was expected to work...

**Comment by davidebbo** [comment]
Yes, looks like it's missing from https://github.com/projectkudu/KuduScript/blob/master/lib/templates/deploy.batch.aspnet.5.template. Want to send PR to fix?

**Comment by jt000** [comment]
No problem. Done... Thanks!
