### ISSUE TITLE
Linux asp .net core deployment: generates default deploy.cmd then tries to find/execute deploy.sh and fails

### ISSUE THREAD

**Issue by atmeet** [projectkudu/KuduScript#62]
Hello, I am testing deployment to Linux for my .net core website.
Looking at the code for generateAspNetCoreDeploymentScript in generator.js, there is a check that for .net core apps the only types allowed are .cmd and .posh. Is this still valid for Linux .net core Apps since during the next execution step it looks for deploy.sh to run.
Also, I could not find a way to modify the "azure site deploymentscript" parameters via the appconfig settings in the portal. Is that possibly just like the .deployment overrides. I believe I can locally generate and upload but was hoping that the default generation would consider the platform (isWindows). Thanks.

**Comment by nickwalkmsft** [comment]
Hi @atameet,

.NET Core support on Linux is still pretty limited at the moment. Using Kudu to build applications from source is not yet supported.

This is coming in the future, but for now, running .NET core applications on Linux requires building them first.

**Comment by atmeet** [comment]
Cool.. Thank you @nickwalkmsft.
