### ISSUE TITLE
Allow other build configuration besides "Release" on dotnet publish

### ISSUE THREAD

**Issue by israellot** [projectkudu/KuduScript#83]
Reference https://github.com/projectkudu/KuduScript/blob/f3c79f08ae9bcd38ec49255641928ec480de8874/lib/templates/deploy.posh.aspnet.core.template

Build configuration is fixed on Release. On non core versions of .net we can configure it via SCM_BUILD_ARGS

**Comment by davidebbo** [comment]
Does dotnet.exe support repeating flags such that a later one can override an earlier one? That's what allows `SCM_BUILD_ARGS` to work with msbuild.

**Comment by israellot** [comment]
I ended up using a custom script with this relevant line 
```call :ExecuteCmd dotnet publish "%PROJECT%" --output "%DEPLOYMENT_TEMP%" --configuration "%BUILD_CONFIGURATION%"```

**Comment by davidebbo** [comment]
Sure, with a custom script, you can do whatever you want. But from what I can see, dotnet.exe doesn't support overriding flags the way msbuild does. Other confusing thing is that it doesn't complain if I pass `--configuration bogus`. i.e. pass whatever you want and it seems to ignore it.

in any case, in the future we'll switch to msbuild to build Core projects, so it will become more like non-core.
