### ISSUE TITLE
Default Azure Function App  deployment script is of type Basic Web Site.

### ISSUE THREAD

**Issue by piorot** [projectkudu/KuduScript#85]
**What might be the reason that the way defuault deployment script is generated has changed?
Why is function app not recognized as function app but as "Basic Web Site"?
How is the app type recognized for generating deployment script?**

**Abstract:**
For some reason the defualt deployment script for function app I used successfuly so far stopped working as intended. Newly created function app the is deployed from local git commit stopped installing node packages on remote site. After analyzing the default deployment script downloaded from portal after failed deployment (failed = no `npm install` fired) it seems there is no longer npm install command there. Moreover after analyzing code here it seems for me that the deployment script is mistekenly generated for Basic Web Site not Function App. 

**Situation description :** 
There is a script that creates azure infrastructure (various services). The python script uses azure-cli 2.0. One of services created with use of the script is function app. The command used is following :
 `x = subprocess.run("az functionapp create -n " + functionName + " --storage-account "  + storageAccount + " --plan " + servicePlan + " -l" , shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`

The second script deploys node.js function app by committing and pushing to azure git repo.

As I have available history of deployments I see that previous deployments were printing 

> remote: Generating deployment script for function App

and latest prints 

> remote: Generating deployment script for Web Site       

The way I create function app has not changed same as the way I deploy code.

Below is the **default** deployment script I downloaded today from kudu ->tools -> Download deployment script that was converted to text to be able to post it here.

[deploy.txt](https://github.com/projectkudu/KuduScript/files/1351693/deploy.txt)

**Steps to reproduce**
It seems I cannot reproduce this behaviour. Anytime I create new function app either by clicking in portal or by firing command in portal terminal or even by firing exactly the same script the function app I get is properly recognized as function app and the log I get is:
> remote: Generating deployment script for function App

**Comment by davidebbo** [comment]
So you mean if you take the exact same repository and push it to a new empty Function App, it deploys correctly? But just on the one Function App, it doesn't?

If so, can you share the name of your app, directly or [indirectly](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately)?

**Comment by piorot** [comment]
Hi there.

The current situation is following. The script that creates, among others, function app, gives different result dependently where it is run. Namely when I run it on my msdn developer subscription the function app that gets created and recognized by deployment scrript generator as a function app. When it is run in "the company subscription" it gets recognized as basic website. The problem has appeared suddenly - it was not so from the beginning. How come can a function app be recognized as basic website? What influances the recognition.

Regarding the name sharing (even indirectly) the question that arises is what it exactly means for company rescources security as there are some sensitive data the comapny is concerned about.

Please also have in mind that the issue for us is somehow workedaround as we provided custom deployment script which in our case run npm install on azure side which is not made for basic webiste default deployment script.

**Comment by davidebbo** [comment]
So in both the working and non-working cases, you are able to repro this on brand new apps that your script create? If so, can you simply create dummy throwaway apps to repro and share their names? Or sharing invocation IDs as per that post works as well, and is not meaningful to anyone outside of the Azure Functions team.

An addition, try going to https://{app}.scm.azurewebsites.net/ in both cases and sharing the Kudu build you see at the top?

**Comment by piorot** [comment]
I will update this topic in a few days.

**Comment by piorot** [comment]
Can be closed. I never had time to get back to this after the issue was solved with described workaround : 

> Please also have in mind that the issue for us is somehow worked around as we provided custom deployment script which in our case run npm install on azure side which is not made for basic website default deployment script.

 I have no access to resources when it might be reproduced any more.
