### ISSUE TITLE
error: Only batch script files are supported for function App  - for JavaScript Function App

### ISSUE THREAD

**Issue by sebbsan** [projectkudu/KuduScript#88]
Hi,
I am trying to deploy a JavaScript Function App to Azure. However I get the error message `error: Only batch script files are supported for function App`.
What can cause this error?

I was triggering a build through the git integration.
Detailed log output is:

> :::::::::::::: log.log :::::::::::::: 
> 2017-11-21T17:22:58.4132910Z,Updating branch '8a7cb2d0d1211305eef99deec082da5501f56e64'., 880855f9-c7b3-47cf-bf3f-773ce1ac0f05,0 
> 2017-11-21T17:22:59.2138570Z,Updating submodules.,72526e2b-9f58-47a1-b493-899e3962b016,0 2017-11-21T17:22:59.3622250Z,Preparing deployment for commit id '8a7cb2d0d1'.,582835b0-c3d6-49d1-a3e6-54c5be02bdc8,0 2017-11-21T17:23:00.2594900Z,Generating deployment script.,94d00c16-854c-49d1-8be2-36db8a654251,0 2017-11-21T17:23:00.5860790Z,Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "/home/site/repository" -o "/home/site/deployments/tools" --functionApp --sitePath "/home/site/repository"'.,,0 2017-11-21T17:23:01.7712540Z,Generating deployment script for function App,,0 2017-11-21T17:23:01.7980550Z,error: Only batch script files are supported for function App,,1 2017-11-21T17:23:01.8517310Z,error: Only batch script files are supported for function App\n/opt/Kudu/bin/Scripts/starter.sh "/opt/Kudu/bin/node_modules/.bin/kuduscript" -y --no-dot-deployment -r "/home/site/repository" -o "/home/site/deployments/tools" --functionApp --sitePath "/home/site/repository",,2 2017-11-21T17:23:02.2706970Z,App container will begin restart within 10 seconds.,244baa05-fb96-41e5-b570-c2dcd3b9087e,0

I am using `Runtime version: 2.0.1.0 (~1) ` for the Function App. 
My `host.json` is empty though, I downloaded it from the Azure console and there were no options specified inside. Is there anything I am missing?

thanks
-Sebastian

**Comment by davidebbo** [comment]
> I am using Runtime version: 2.0.1.0 (~1) for the Function App

Can you clarify this? If you're using ~1, you should be running `1.0.11388.0`.

**Comment by sebbsan** [comment]
@davidebbo well that's another weird thing.. in my Azure Portal it says 
```
Runtime version: 2.0.1.0 (~1)
```
I wanted to downgrade by setting `FUNCTIONS_EXTENSION_VERSION = "~1"` and that's what I got.

I saw that there was a change recently in lib/generator._js  - 
https://github.com/projectkudu/KuduScript/commit/39c5665a08f2ae50c0f853f5d44f574265ed3118  

it looks like there might be a version mismatch of the cloud runtime and the KuduScrupt version within Azure, at least in my region eu-west? I guess that's something I need to raise that with Azure Support...

**Comment by sebbsan** [comment]
@davidebbo  actually I got it working now. I had a Linux runtime, which doesn't seem to be fully supported yet. I spun up a Windows runtime and the deployment via local git works like a charm :)
